// UI Actions
export const SET_SCREEN = 'SET_SCREEN';

// Player Actions
export const UPDATE_PLAYER_HEALTH = 'UPDATE_PLAYER_HEALTH';
export const UPDATE_PLAYER_MANA = 'UPDATE_PLAYER_MANA';
export const ADD_CARD_TO_HAND = 'ADD_CARD_TO_HAND';
export const REMOVE_CARD_FROM_HAND = 'REMOVE_CARD_FROM_HAND';
export const ADD_EFFECT_TO_PLAYER = 'ADD_EFFECT_TO_PLAYER';
export const REMOVE_EFFECT_FROM_PLAYER = 'REMOVE_EFFECT_FROM_PLAYER';
export const RESET_PLAYER = 'RESET_PLAYER';

// Player State Management Actions
export const UPDATE_SPIRIT_STRAIN = 'UPDATE_SPIRIT_STRAIN';
export const ADD_CARD_TO_COLLECTION = 'ADD_CARD_TO_COLLECTION';
export const REMOVE_CARD_FROM_COLLECTION = 'REMOVE_CARD_FROM_COLLECTION';
export const SET_DECK = 'SET_DECK';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const GAIN_EXPERIENCE = 'GAIN_EXPERIENCE';
export const LEVEL_UP = 'LEVEL_UP';
export const UPDATE_REPUTATION = 'UPDATE_REPUTATION';
export const UPDATE_STATISTIC = 'UPDATE_STATISTIC';
export const UNLOCK_ACHIEVEMENT = 'UNLOCK_ACHIEVEMENT';
export const UPDATE_ACHIEVEMENT_PROGRESS = 'UPDATE_ACHIEVEMENT_PROGRESS';
export const UPDATE_PREFERENCE = 'UPDATE_PREFERENCE';

// Combat Actions
export const START_COMBAT = 'START_COMBAT';
export const END_COMBAT = 'END_COMBAT';
export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD';
export const SET_SELECTED_TARGET = 'SET_SELECTED_TARGET';
export const UPDATE_ENEMY = 'UPDATE_ENEMY';
export const REMOVE_ENEMY = 'REMOVE_ENEMY';
export const INCREMENT_TURN = 'INCREMENT_TURN';

// Patient Actions
export const ADD_PATIENT = 'ADD_PATIENT';
export const SET_CURRENT_PATIENT = 'SET_CURRENT_PATIENT';
export const COMPLETE_PATIENT = 'COMPLETE_PATIENT';
export const UPDATE_WAITING_LIST = 'UPDATE_WAITING_LIST';

// Stats Actions
export const INCREMENT_PATIENTS_HEALED = 'INCREMENT_PATIENTS_HEALED';
export const INCREMENT_CARDS_PLAYED = 'INCREMENT_CARDS_PLAYED';
export const UPDATE_DAMAGE_DEALT = 'UPDATE_DAMAGE_DEALT';
export const UPDATE_HEALING_DONE = 'UPDATE_HEALING_DONE';

// System Actions
export const RESET_STATE = 'RESET_STATE';
export const LOAD_STATE = 'LOAD_STATE';
